### ISSUE TITLE
Create docker for Nginx

### ISSUE THREAD

**Issue by ollemuhr** [fareoffice/modsecurity-docker#1]
https://github.com/SpiderLabs/ModSecurity-nginx

**Comment by ysoldak** [comment]
Have PR #5 and merged, shall see how it flies

**Comment by krish512** [comment]
Try https://hub.docker.com/r/krish512/modsecurity/, it is already built with latest ModSecurity CRS rules

**Comment by ysoldak** [comment]
Already implemented
