### ISSUE TITLE
Failed restart

### ISSUE THREAD

**Issue by slopokeit** [fareoffice/modsecurity-docker#6]
Should docker restart the service whether it be manual or due to a crash, if one had manually supplied BEFORE or AFTER rules with a unique id#, then the service will crash with a fatal error.

This occurs because the logic in main.sh will forever append the rules into the REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf and RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf respectively.   So if the service were to restart, the previous rules are still there and now duplicate entries are created.  This caused the underlying modsecurity service to crash.

To fix, simply blank out the rule configuration files before processing the custom rules.

```
#blank out rules file in prep for below
echo "" > /etc/nginx/modsecurity.d/owasp-crs/rules/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf

names=`env | grep SEC_RULE_AFTER_ | sed 's/=.*//'`
if [ "$names" != "" ]; then
  while read name; do
    eval value='$'"${name}"
    echo "${value}" >> /etc/nginx/modsecurity.d/owasp-crs/rules/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf
  done <<< "$names"
  echo "RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf"
  cat /etc/nginx/modsecurity.d/owasp-crs/rules/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf
fi
```

**Comment by ysoldak** [comment]
Hey, good catch! Thanks, we shall definitely fix this.

Running modsec container on Kubernetes we actually never experienced this problem, since containers are re-created every time and never restarted.
